name: Deploy to Render

on:
  push:
    branches:
      - main
      - staging
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Render (Production)
        if: github.ref == 'refs/heads/main'
        run: |
          curl -X POST "$RENDER_DEPLOY_HOOK_PROD"

      - name: Deploy to Render (Staging)
        if: github.ref == 'refs/heads/staging'
        run: |
          curl -X POST "$RENDER_DEPLOY_HOOK_STAGING"

      - name: Deploy to Render (Development)
        if: github.ref == 'refs/heads/dev'
        run: |
          curl -X POST "$RENDER_DEPLOY_HOOK_DEV"
